import cv2
import numpy
img=cv2.imread('wallpaper-night.jpg',0)
kernel=numpy.ones((5,5),numpy.uint8)
erosion=cv2.erode(img,kernel,iterations=1)
dilation=cv2.dilate(img,kernel,iterations=1)
opening=cv2.morphologyEx(img,cv2.MORPH_OPEN,kernel)
closing=cv2.morphologyEx(img,cv2.MORPH_CLOSE,kernel)
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.imshow('eroded',erosion)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.imshow('dilated',dilation)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.imshow('opening',opening)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.imshow('closing',closing)
cv2.waitKey(0)
cv2.destroyAllWindows()

